In [1]:
import sys
sys.path.append('../')

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import linear_model
from sklearn.metrics import confusion_matrix, classification_report

from rtbm import RTBM
import rtbm as rtbm
import minimizer

In [5]:
# Load MNIST dataset
MNIST_train = pd.read_csv('~/data/mnist_train.csv', delimiter=",",header=None).values
MNIST_test  = pd.read_csv('~/data/mnist_test.csv', delimiter=",",header=None).values

# Prepare data (normalized onto [0,1])
Y_train = MNIST_train[0:,0]
X_train = MNIST_train[0:,1:]/255.0

Y_test = MNIST_test[:,0]
X_test = MNIST_test[:,1:]/255.0

In [3]:
# Visualize individual pics
i=10
print(Y_train[i])
I=np.reshape(X_train[i], (28,28))
plt.imshow(I, interpolation='nearest',  cmap='gray_r')
plt.show()

3


TclError: couldn't connect to display "localhost:10.0"

# Logistic regression baseline

In [6]:
# Logistic regression baseline
logreg = linear_model.LogisticRegression()

logreg.fit(X_train,Y_train)
P=logreg.predict(X_test)

print(classification_report(Y_test,P))
print(confusion_matrix(Y_test, P))


             precision    recall  f1-score   support

          0       0.95      0.98      0.96       980
          1       0.96      0.98      0.97      1135
          2       0.94      0.89      0.91      1032
          3       0.89      0.91      0.90      1010
          4       0.92      0.93      0.93       982
          5       0.89      0.86      0.88       892
          6       0.94      0.95      0.94       958
          7       0.93      0.92      0.93      1028
          8       0.87      0.88      0.87       974
          9       0.90      0.89      0.89      1009

avg / total       0.92      0.92      0.92     10000

[[ 960    0    1    2    0    5    6    3    1    2]
 [   0 1112    3    1    0    1    5    1   12    0]
 [   8    8  920   20    9    5   10   11   37    4]
 [   4    0   17  919    2   22    4   12   21    9]
 [   1    2    5    3  914    0   10    2    7   38]
 [  10    2    0   42   10  769   17    7   28    7]
 [   9    3    7    2    6   20  907    1  

# RTBM

In [ ]:
rtbm.precision = 1e-6


R = RTBM(3,2)
R.random_init()

In [ ]:
R.w

In [ ]:
rtbm.precision = 1e-6


R = RTBM(784,2)
R.set_bound(100)
minim = minimizer.CMA()
sol = minim.train(R, np.transpose(X_train))

In [ ]:
X_train.shape

In [ ]:
test